# Load packages -----------------------------------------------------------

require(box, quietly = TRUE)
require(car, quietly = TRUE)
require(dplyr, quietly = TRUE)
require(ggbeeswarm, quietly = TRUE)
require(ggimage, quietly = TRUE)
require(ggplot2, quietly = TRUE)
require(ggpubr, quietly = TRUE)
require(ggstatsplot, quietly = TRUE)
require(grid, quietly = TRUE)
require(gridExtra, quietly = TRUE)
require(htmlwidgets, quietly = TRUE)
require(kableExtra, quietly = TRUE)
require(nortest, quietly = TRUE)
require(openxlsx, quietly = TRUE)
require(patchwork, quietly = TRUE)
require(plotly, quietly = TRUE)
require(purrr, quietly = TRUE)
require(readr, quietly = TRUE)
require(readxl, quietly = TRUE)
require(SIBER, quietly = TRUE)
require(tibble, quietly = TRUE)
require(tidyverse, quietly = TRUE)

